Specification of an explicit order for object files according to their link time
The setting of the variables “OBJS” and “OPTOBJS” was adjusted in this
make script. This had the consequence that the ordering of elements
was also changed for the constructed file lists. The generation of
corresponding object code libraries succeeded still.

This software area can eventually be changed by adjustments for the bug report
“singly unlinkable cma orders silently allowed” (from 2015-02-11).
https://caml.inria.fr/mantis/view.php?id=6778

But an error message was displayed by the final link command.


elfring@Sonne:~/Projekte/Coccinelle/20160205> LANG=C make --no-builtin-rules V=1
…
/usr/bin/ocamlopt.opt … -o spatch.opt … ctl/ctl.cmxa …
File "_none_", line 1:
Error: No implementations provided for the following modules:
         Pretty_print_ctl referenced from ctl/ctl.cmxa(Ctl_engine)
make[3]: *** [Makefile:227: spatch.opt] Error 2
…


The error reason was clarified for the bug report “Checking processes for
resolving of references from module implementations by the OCaml linker”
(from 2017-06-25).
https://caml.inria.fr/mantis/view.php?id=7566

An explicit order was therefore chosen for the new variable “working_order”
which should express a dependency specification usable also at link time.
It is different from the source file listing now.


Fixes: 9597598779f3604272621f6d42ead79eaafad2a8 ("Bug 104: Improve some dependency specifications in make rules")

Signed-off-by: Markus Elfring <elfring@users.sourceforge.net>