Bug #104: Improve some dependency specifications in make rules
A bit of progress was achieved with one experiment for build script adjustments.
Further changes can be tried out. Unfortunately, an error message like the
following from the program “GNU Make 4.2.1-1.7” was noticed then.
https://systeme.lip6.fr/pipermail/cocci/2017-June/004181.html

…
/usr/bin/ocamlopt.opt …
File "cocci.ml", line 1:
Error: Could not find the .cmi file for interface cocci.mli.
make[3]: *** [Makefile:533: cocci.cmx] Error 2
…


Suffix rules were used to generate the desired software components usually.
These rules were correctly used in the documented sense that no extra
prerequisites were specified there. This means also that usual dependencies
on other software modules were not directly expressed by default.
Extra dependencies were integrated by inclusion of the make script “.depend”
which was automatically generated by the tool “ocamldep”.

Further tests pointed places out despite of this detail where the build approach
failed in a “special” software development configuration.


The affected make rules were also repeated in several scripts. They were moved
to a separate script and replaced by pattern rules with the addition of an
explicit dependency on interface descriptions in the form of mli files for
the programming language “OCaml”. This change increased the relevance for
these files. But it had also the consequence that tolerance had to be
explicitly expressed for software areas which work also without such
interface descriptions. The make rules were extended as needed then.


Further build tests were performed which showed unexpected results.

Open issue 1)
elfring@Sonne:~/Projekte/Coccinelle/20160205/globals> make clean && LANG=C make --no-builtin-rules V=1 && make clean && LANG=C make --no-builtin-rules -j4 V=1
rm -f …
…
/usr/bin/ocamlc.opt -unsafe -I ../commons -I /home/elfring/Projekte/Coccinelle/20160205/bundles/pcre/ -a -o globals.cma config.cmo flag.cmo regexp_pcre.cmo regexp.cmo iteration.cmo
rm -f …
…
/usr/bin/ocamlc.opt -unsafe -I ../commons -I /home/elfring/Projekte/Coccinelle/20160205/bundles/pcre/ -c iteration.mli
make: *** No rule to make target 'flag.cmi', needed by 'iteration.cmo'.  Stop.
…


Three non-parallel build commands worked before the parallel build try failed.
It is unclear then if the provided dependency specifications are really
still incomplete.
https://systeme.lip6.fr/pipermail/cocci/2017-June/004208.html
https://lists.gnu.org/archive/html/bug-make/2017-06/msg00185.html


Open issue 2)

elfring@Sonne:~/Projekte/Coccinelle/20160205> LANG=C make --no-builtin-rules V=1
…
/usr/bin/ocamlopt.opt … -o spatch.opt … ctl/ctl.cmxa …
File "_none_", line 1:
Error: No implementations provided for the following modules:
         Pretty_print_ctl referenced from ctl/ctl.cmxa(Ctl_engine)
make[3]: *** [Makefile:227: spatch.opt] Error 2
make[3]: Leaving directory '/home/elfring/Projekte/Coccinelle/20160205'
make[2]: *** [Makefile:166: opt-compil] Error 2
make[2]: Leaving directory '/home/elfring/Projekte/Coccinelle/20160205'
make[1]: *** [Makefile:146: all-release] Error 2
make[1]: Leaving directory '/home/elfring/Projekte/Coccinelle/20160205'
make: *** [Makefile:123: all] Error 2


The desired linking step failed for this module combination while using
the software “OCaml 4.03.0-3.1”.


It is hoped that the intermediate software development results can become
another useful information source for general inspiration and better
clarification of remaining open issues.

Signed-off-by: Markus Elfring <elfring@users.sourceforge.net>